spring:
  application:
    name: hello-service

server:
  port: 8001

grpc:
  port: 6001

eureka:
  instance:
    nonSecurePort: ${grpc.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/